-- Create PRICE_HISTORY table
CREATE TABLE PRICE_HISTORY (
    HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    OLD_PRICE DECIMAL(18,2),
    NEW_PRICE DECIMAL(18,2) NOT NULL,
    PRICE_CHANGE DECIMAL(18,2),
    PERCENTAGE_CHANGE DECIMAL(5,2),
    YEAR INT NOT NULL,
    RECORDED_DATE DATETIME DEFAULT GETDATE(),
    NOTES VARCHAR(1000),
    CREATED_BY VARCHAR(50),
    CONSTRAINT FK_PRICE_HISTORY_PRODUCTS 
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create index for better performance
CREATE INDEX IX_PRICE_HISTORY_PRODUCT_ID ON PRICE_HISTORY(PRODUCT_ID);
CREATE INDEX IX_PRICE_HISTORY_YEAR ON PRICE_HISTORY(YEAR);
CREATE INDEX IX_PRICE_HISTORY_RECORDED_DATE ON PRICE_HISTORY(RECORDED_DATE);
