-- เพิ่มฟิลด์ ORGCODE3 ในตาราง REQUISITIONS
ALTER TABLE REQUISITIONS ADD ORGCODE3 VARCHAR(50);

-- เพิ่มฟิลด์ ORGCODE3 ในตาราง USERS (ถ้ายังไม่มี)
ALTER TABLE USERS ADD ORGCODE3 VARCHAR(50);

-- สร้าง index สำหรับการค้นหาตาม orgcode3
CREATE INDEX IX_REQUISITIONS_ORGCODE3 ON REQUISITIONS(ORGCODE3);
CREATE INDEX IX_USERS_ORGCODE3 ON USERS(ORGCODE3);

-- อัปเดตข้อมูล orgcode3 จาก userWithRoles view
UPDATE REQUISITIONS 
SET ORGCODE3 = (
    SELECT orgcode3 
    FROM userWithRoles 
    WHERE userWithRoles.AdLoginName = REQUISITIONS.USER_ID
)
WHERE ORGCODE3 IS NULL;

UPDATE USERS 
SET ORGCODE3 = (
    SELECT orgcode3 
    FROM userWithRoles 
    WHERE userWithRoles.AdLoginName = USERS.USER_ID
)
WHERE ORGCODE3 IS NULL; 