-- เพิ่มฟิลด์ ADMIN_VIEWED_AT ในตาราง REQUISITIONS
ALTER TABLE REQUISITIONS 
ADD ADMIN_VIEWED_AT DATETIME NULL;

-- เพิ่ม index เพื่อประสิทธิภาพในการค้นหา
CREATE INDEX IX_REQUISITIONS_ADMIN_VIEWED_AT ON REQUISITIONS (ADMIN_VIEWED_AT);

-- อัพเดทข้อมูลที่มีอยู่ให้ ADMIN_VIEWED_AT เป็น NULL (ยังไม่ได้ดู)
UPDATE REQUISITIONS 
SET ADMIN_VIEWED_AT = NULL 
WHERE ADMIN_VIEWED_AT IS NULL;

PRINT '✅ เพิ่มฟิลด์ ADMIN_VIEWED_AT เรียบร้อยแล้ว';
