-- สร้างตาราง PRODUCT_AUDIT_LOG สำหรับเก็บประวัติการเปลี่ยนแปลงสินค้า
CREATE TABLE PRODUCT_AUDIT_LOG (
    AUDIT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    ACTION_TYPE VARCHAR(20) NOT NULL, -- CREATE, UPDATE, DELETE
    OLD_DATA TEXT NULL, -- JSON string ของข้อมูลเก่า
    NEW_DATA TEXT NULL, -- JSON string ของข้อมูลใหม่
    CHANGED_BY VARCHAR(50) NOT NULL,
    CHANGED_AT DATETIME DEFAULT GETDATE(),
    IP_ADDRESS VARCHAR(45) NULL,
    USER_AGENT VARCHAR(500) NULL,
    NOTES VARCHAR(1000) NULL,
    
    -- Foreign Key Constraints
    CONSTRAINT FK_PRODUCT_AUDIT_LOG_PRODUCT_ID 
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_AUDIT_LOG_CHANGED_BY 
        FOREIGN KEY (CHANGED_BY) REFERENCES USERS(USER_ID)
);

-- สร้าง Index สำหรับการค้นหาที่เร็วขึ้น
CREATE INDEX IX_PRODUCT_AUDIT_LOG_PRODUCT_ID ON PRODUCT_AUDIT_LOG(PRODUCT_ID);
CREATE INDEX IX_PRODUCT_AUDIT_LOG_CHANGED_AT ON PRODUCT_AUDIT_LOG(CHANGED_AT);
CREATE INDEX IX_PRODUCT_AUDIT_LOG_ACTION_TYPE ON PRODUCT_AUDIT_LOG(ACTION_TYPE);
CREATE INDEX IX_PRODUCT_AUDIT_LOG_CHANGED_BY ON PRODUCT_AUDIT_LOG(CHANGED_BY);
