-- สร้างตาราง PRODUCT_AUDIT_LOG สำหรับเก็บประวัติการเปลี่ยนแปลงสินค้า
-- ต้องรันใน database StationeryDB เท่านั้น

-- เลือก database ที่ถูกต้อง
USE StationeryDB;
GO

-- ตรวจสอบว่าตารางมีอยู่แล้วหรือไม่
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PRODUCT_AUDIT_LOG' AND xtype='U')
BEGIN
    -- สร้างตาราง PRODUCT_AUDIT_LOG
    CREATE TABLE PRODUCT_AUDIT_LOG (
        AUDIT_ID INT IDENTITY(1,1) PRIMARY KEY,
        PRODUCT_ID INT NOT NULL,
        ACTION_TYPE VARCHAR(20) NOT NULL, -- CREATE, UPDATE, DELETE
        OLD_DATA TEXT NULL, -- JSON string ของข้อมูลเก่า
        NEW_DATA TEXT NULL, -- JSON string ของข้อมูลใหม่
        CHANGED_BY VARCHAR(50) NOT NULL,
        CHANGED_AT DATETIME DEFAULT GETDATE(),
        IP_ADDRESS VARCHAR(45) NULL,
        USER_AGENT VARCHAR(500) NULL,
        NOTES VARCHAR(1000) NULL,
        
        -- Foreign Key Constraints
        CONSTRAINT FK_PRODUCT_AUDIT_LOG_PRODUCT_ID 
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
        CONSTRAINT FK_PRODUCT_AUDIT_LOG_CHANGED_BY 
            FOREIGN KEY (CHANGED_BY) REFERENCES USERS(USER_ID)
    );
    
    PRINT 'ตาราง PRODUCT_AUDIT_LOG ถูกสร้างเรียบร้อยแล้ว';
END
ELSE
BEGIN
    PRINT 'ตาราง PRODUCT_AUDIT_LOG มีอยู่แล้ว';
END
GO

-- สร้าง Index สำหรับการค้นหาที่เร็วขึ้น
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRODUCT_AUDIT_LOG_PRODUCT_ID')
BEGIN
    CREATE INDEX IX_PRODUCT_AUDIT_LOG_PRODUCT_ID ON PRODUCT_AUDIT_LOG(PRODUCT_ID);
    PRINT 'Index IX_PRODUCT_AUDIT_LOG_PRODUCT_ID ถูกสร้างเรียบร้อยแล้ว';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRODUCT_AUDIT_LOG_CHANGED_AT')
BEGIN
    CREATE INDEX IX_PRODUCT_AUDIT_LOG_CHANGED_AT ON PRODUCT_AUDIT_LOG(CHANGED_AT);
    PRINT 'Index IX_PRODUCT_AUDIT_LOG_CHANGED_AT ถูกสร้างเรียบร้อยแล้ว';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRODUCT_AUDIT_LOG_ACTION_TYPE')
BEGIN
    CREATE INDEX IX_PRODUCT_AUDIT_LOG_ACTION_TYPE ON PRODUCT_AUDIT_LOG(ACTION_TYPE);
    PRINT 'Index IX_PRODUCT_AUDIT_LOG_ACTION_TYPE ถูกสร้างเรียบร้อยแล้ว';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRODUCT_AUDIT_LOG_CHANGED_BY')
BEGIN
    CREATE INDEX IX_PRODUCT_AUDIT_LOG_CHANGED_BY ON PRODUCT_AUDIT_LOG(CHANGED_BY);
    PRINT 'Index IX_PRODUCT_AUDIT_LOG_CHANGED_BY ถูกสร้างเรียบร้อยแล้ว';
END
GO

-- ตรวจสอบผลลัพธ์
SELECT 'ตาราง PRODUCT_AUDIT_LOG' AS TableName, COUNT(*) AS ColumnCount
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUCT_AUDIT_LOG';

SELECT 'Indexes' AS IndexType, COUNT(*) AS IndexCount
FROM sys.indexes 
WHERE object_id = OBJECT_ID('PRODUCT_AUDIT_LOG') AND name IS NOT NULL;
GO
