-- Create database schema for Stationery Requisition System

-- Product Categories table
CREATE TABLE PRODUCT_CATEGORIES (
    CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL
);

-- Users table
CREATE TABLE USERS (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ROLE VARCHAR(20) CHECK (ROLE IN ('USER', 'MANAGER', 'ADMIN')) NOT NULL,
    DEPARTMENT VARCHAR(50),
    SITE_ID VARCHAR(50),
    CREATED_AT DATETIME DEFAULT GETDATE()
);

-- Products table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    CATEGORY_ID INT FOREIGN KEY REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID),
    STOCK_TYPE VARCHAR(50),
    STOCK_QUANTITY INT DEFAULT 0,
    UNIT_COST DECIMAL(10,2) NOT NULL,
    ORDER_UNIT VARCHAR(20),
    PHOTO_URL VARCHAR(500),
    CREATED_AT DATETIME DEFAULT GETDATE()
);

-- Requisitions table
CREATE TABLE REQUISITIONS (
    REQUISITION_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USERS(USER_ID),
    STATUS VARCHAR(20) CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')) DEFAULT 'PENDING',
    SUBMITTED_AT DATETIME DEFAULT GETDATE(),
    TOTAL_AMOUNT DECIMAL(10,2),
    SITE_ID VARCHAR(50),
    ISSUE_NOTE VARCHAR(500)
);

-- Requisition Items table
CREATE TABLE REQUISITION_ITEMS (
    ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUISITION_ID INT FOREIGN KEY REFERENCES REQUISITIONS(REQUISITION_ID),
    PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL
);

-- Approvals table
CREATE TABLE APPROVALS (
    APPROVAL_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUISITION_ID INT FOREIGN KEY REFERENCES REQUISITIONS(REQUISITION_ID),
    APPROVED_BY INT FOREIGN KEY REFERENCES USERS(USER_ID),
    STATUS VARCHAR(20) CHECK (STATUS IN ('APPROVED', 'REJECTED')),
    APPROVED_AT DATETIME DEFAULT GETDATE(),
    NOTE VARCHAR(500)
);

-- Export Logs table
CREATE TABLE EXPORT_LOGS (
    EXPORT_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUISITION_ID INT FOREIGN KEY REFERENCES REQUISITIONS(REQUISITION_ID),
    EXPORTED_BY INT FOREIGN KEY REFERENCES USERS(USER_ID),
    FILE_TYPE VARCHAR(10) CHECK (FILE_TYPE IN ('PDF', 'EXCEL')),
    EXPORTED_AT DATETIME DEFAULT GETDATE()
);

-- Email Logs table
CREATE TABLE EMAIL_LOGS (
    EMAIL_ID INT IDENTITY(1,1) PRIMARY KEY,
    TO_USER_ID INT FOREIGN KEY REFERENCES USERS(USER_ID),
    SUBJECT VARCHAR(200),
    BODY TEXT,
    SENT_AT DATETIME DEFAULT GETDATE(),
    STATUS VARCHAR(20) DEFAULT 'SENT' CHECK (STATUS IN ('SENT', 'FAILED'))
);

-- Status History table
CREATE TABLE STATUS_HISTORY (
    STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUISITION_ID INT FOREIGN KEY REFERENCES REQUISITIONS(REQUISITION_ID),
    STATUS VARCHAR(20),
    CHANGED_BY INT FOREIGN KEY REFERENCES USERS(USER_ID),
    CHANGED_AT DATETIME DEFAULT GETDATE(),
    COMMENT VARCHAR(500)
);
