USE StationeryDB;
GO

-- ลบ foreign key constraint เดิม
ALTER TABLE PRODUCT_AUDIT_LOG DROP CONSTRAINT FK_PRODUCT_AUDIT_LOG_PRODUCT_ID;
GO

-- สร้าง foreign key constraint ใหม่ที่อนุญาตให้ลบสินค้าได้
ALTER TABLE PRODUCT_AUDIT_LOG 
ADD CONSTRAINT FK_PRODUCT_AUDIT_LOG_PRODUCT_ID 
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) 
ON DELETE SET NULL;
GO
