-- Script สำหรับสร้างตาราง PRICE_HISTORY
-- รันใน SQL Server Management Studio หรือ Azure Data Studio

USE [your_database_name]; -- เปลี่ยนชื่อฐานข้อมูลตามจริง

-- สร้างตาราง PRICE_HISTORY
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRICE_HISTORY]') AND type in (N'U'))
BEGIN
    CREATE TABLE PRICE_HISTORY (
        HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
        PRODUCT_ID INT NOT NULL,
        OLD_PRICE DECIMAL(18,2),
        NEW_PRICE DECIMAL(18,2) NOT NULL,
        PRICE_CHANGE DECIMAL(18,2),
        PERCENTAGE_CHANGE DECIMAL(5,2),
        YEAR INT NOT NULL,
        RECORDED_DATE DATETIME DEFAULT GETDATE(),
        NOTES VARCHAR(1000),
        CREATED_BY VARCHAR(50)
    );
    
    PRINT 'Table PRICE_HISTORY created successfully';
END
ELSE
BEGIN
    PRINT 'Table PRICE_HISTORY already exists';
END

-- สร้าง Foreign Key
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PRICE_HISTORY_PRODUCTS]') AND parent_object_id = OBJECT_ID(N'[dbo].[PRICE_HISTORY]'))
BEGIN
    ALTER TABLE PRICE_HISTORY 
    ADD CONSTRAINT FK_PRICE_HISTORY_PRODUCTS 
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID);
    
    PRINT 'Foreign Key FK_PRICE_HISTORY_PRODUCTS created successfully';
END
ELSE
BEGIN
    PRINT 'Foreign Key FK_PRICE_HISTORY_PRODUCTS already exists';
END

-- สร้าง Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRICE_HISTORY_PRODUCT_ID' AND object_id = OBJECT_ID('PRICE_HISTORY'))
BEGIN
    CREATE INDEX IX_PRICE_HISTORY_PRODUCT_ID ON PRICE_HISTORY(PRODUCT_ID);
    PRINT 'Index IX_PRICE_HISTORY_PRODUCT_ID created successfully';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRICE_HISTORY_YEAR' AND object_id = OBJECT_ID('PRICE_HISTORY'))
BEGIN
    CREATE INDEX IX_PRICE_HISTORY_YEAR ON PRICE_HISTORY(YEAR);
    PRINT 'Index IX_PRICE_HISTORY_YEAR created successfully';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRICE_HISTORY_RECORDED_DATE' AND object_id = OBJECT_ID('PRICE_HISTORY'))
BEGIN
    CREATE INDEX IX_PRICE_HISTORY_RECORDED_DATE ON PRICE_HISTORY(RECORDED_DATE);
    PRINT 'Index IX_PRICE_HISTORY_RECORDED_DATE created successfully';
END

PRINT 'Migration completed successfully!';
